/* This file is part of the KDE project
 * SPDX-FileCopyrightText: 2009 Jan Hambrecht <jaham@gmx.net>
 *
 * SPDX-License-Identifier: LGPL-2.0-or-later
 */

#include "SvgUtil.h"
#include "SvgGraphicContext.h"

#include <KoUnit.h>
#include <KoSvgText.h>

#include <QString>
#include <QRectF>
#include <QStringList>
#include <math.h>
#include "kis_global.h"

#include <KoXmlWriter.h>
#include "kis_dom_utils.h"

#define DPI 72.0

#define DEG2RAD(degree) degree/180.0*M_PI

double SvgUtil::ptToPx(SvgGraphicsContext *gc, double value)
{
    return value * gc->pixelsPerInch / DPI;
}

QString SvgUtil::toPercentage(qreal value)
{
    return KisDomUtils::toString(value * 100.0) + "%";
}

double SvgUtil::fromPercentage(QString s, bool *ok)
{
    if (s.endsWith('%'))
        return KisDomUtils::toDouble(s.remove('%'), ok) / 100.0;
    else
        return KisDomUtils::toDouble(s, ok);
}

QString SvgUtil::transformToString(const QTransform &transform)
{
    if (transform.isIdentity())
        return QString();

    if (transform.type() == QTransform::TxTranslate) {
        return QString("translate(%1, %2)")
                     .arg(KisDomUtils::toString(toUserSpace(transform.dx())))
                     .arg(KisDomUtils::toString(toUserSpace(transform.dy())));
    } else {
        return QString("matrix(%1 %2 %3 %4 %5 %6)")
                     .arg(KisDomUtils::toString(transform.m11()))
                     .arg(KisDomUtils::toString(transform.m12()))
                     .arg(KisDomUtils::toString(transform.m21()))
                     .arg(KisDomUtils::toString(transform.m22()))
                     .arg(KisDomUtils::toString(toUserSpace(transform.dx())))
                     .arg(KisDomUtils::toString(toUserSpace(transform.dy())));
    }
}

void SvgUtil::writeTransformAttributeLazy(const QString &name, const QTransform &transform, KoXmlWriter &shapeWriter)
{
    const QString value = transformToString(transform);

    if (!value.isEmpty()) {
        shapeWriter.addAttribute(name.toLatin1().data(), value);
    }
}

bool SvgUtil::parseViewBox(const QDomElement &e,
                           const QRectF &elementBounds,
                           QRectF *_viewRect, QTransform *_viewTransform)
{
    KIS_ASSERT(_viewRect);
    KIS_ASSERT(_viewTransform);

    QString viewBoxStr = e.attribute("viewBox");
    if (viewBoxStr.isEmpty()) return false;

    bool result = false;

    QRectF viewBoxRect;
    // this is a workaround for bug 260429 for a file generated by blender
    // who has px in the viewbox which is wrong.
    // reported as bug https://developer.blender.org/T30971
    viewBoxStr.remove("px");

    QStringList points = viewBoxStr.replace(',', ' ').simplified().split(' ');
    if (points.count() == 4) {
        viewBoxRect.setX(SvgUtil::fromUserSpace(points[0].toDouble()));
        viewBoxRect.setY(SvgUtil::fromUserSpace(points[1].toDouble()));
        viewBoxRect.setWidth(SvgUtil::fromUserSpace(points[2].toDouble()));
        viewBoxRect.setHeight(SvgUtil::fromUserSpace(points[3].toDouble()));

        result = true;
    } else {
        // TODO: WARNING!
    }

    if (!result) return false;

    qreal scaleX = 1;
    if (!qFuzzyCompare(elementBounds.width(), viewBoxRect.width())) {
        scaleX = elementBounds.width() / viewBoxRect.width();
    }
    qreal scaleY = 1;
    if (!qFuzzyCompare(elementBounds.height(), viewBoxRect.height())) {
        scaleY = elementBounds.height() / viewBoxRect.height();
    }

    QTransform viewBoxTransform =
        QTransform::fromTranslate(-viewBoxRect.x(), -viewBoxRect.y()) *
        QTransform::fromScale(scaleX, scaleY) *
        QTransform::fromTranslate(elementBounds.x(), elementBounds.y());

    const QString aspectString = e.attribute("preserveAspectRatio");
    // give initial value if value not defined
    PreserveAspectRatioParser p( (!aspectString.isEmpty())? aspectString : QString("xMidYMid meet"));
    parseAspectRatio(p, elementBounds, viewBoxRect, &viewBoxTransform);

    *_viewRect = viewBoxRect;
    *_viewTransform = viewBoxTransform;

    return result;
}

qreal SvgUtil::parseUnit(SvgGraphicsContext *gc, const KoSvgTextProperties &resolved, QStringView unit, bool horiz, bool vert, const QRectF &bbox)
{
    if (unit.isEmpty())
        return 0.0;
    QByteArray unitLatin1 = unit.toLatin1();
    // TODO : percentage?
    const char *start = unitLatin1.data();
    if (!start) {
        return 0.0;
    }
    KoSvgText::CssLengthPercentage length = parseUnitStruct(gc, unit, horiz, vert, bbox);
    length.convertToAbsolute(resolved.metrics(), resolved.fontSize().value);

    return length.value;
}

KoSvgText::CssLengthPercentage SvgUtil::parseUnitStruct(SvgGraphicsContext *gc, QStringView unit, bool horiz, bool vert, const QRectF &bbox)
{
    return parseUnitStructImpl(gc, unit, horiz, vert, bbox, true);
}

KoSvgText::CssLengthPercentage SvgUtil::parseTextUnitStruct(SvgGraphicsContext *gc, QStringView unit)
{
    return parseUnitStructImpl(gc, unit, false, false, QRectF(), false);
}

KoSvgText::CssLengthPercentage SvgUtil::parseUnitStructImpl(SvgGraphicsContext *gc, QStringView unit, bool horiz, bool vert, const QRectF &bbox, bool percentageViewBox)
{
    KoSvgText::CssLengthPercentage length;

    if (unit.isEmpty())
        return length;
    QByteArray unitLatin1 = unit.trimmed().toLatin1();
    // TODO : percentage?
    const char *start = unitLatin1.data();
    if (!start) {
        return length;
    }
    const char *end = parseNumber(start, length.value);

    if (int(end - start) < unit.length()) {
        if (unit.right(2) == QLatin1String("px"))
            length.value = SvgUtil::fromUserSpace(length.value);
        else if (unit.right(2) == QLatin1String("pt"))
            length.value = ptToPx(gc, length.value);
        else if (unit.right(2) == QLatin1String("cm"))
            length.value = ptToPx(gc, CM_TO_POINT(length.value));
        else if (unit.right(2) == QLatin1String("pc"))
            length.value = ptToPx(gc, PI_TO_POINT(length.value));
        else if (unit.right(2) == QLatin1String("mm"))
            length.value = ptToPx(gc, MM_TO_POINT(length.value));
        else if (unit.right(2) == QLatin1String("in"))
            length.value = ptToPx(gc, INCH_TO_POINT(length.value));
        else if (unit.right(2) == QLatin1String("em")) {
            length.unit = KoSvgText::CssLengthPercentage::Em;
        } else if (unit.right(2) == QLatin1String("ex")) {
            length.unit = KoSvgText::CssLengthPercentage::Ex;
        } else if (unit.right(3) == QLatin1String("cap")) {
            length.unit = KoSvgText::CssLengthPercentage::Cap;
        } else if (unit.right(2) == QLatin1String("ch")) {
            length.unit = KoSvgText::CssLengthPercentage::Ch;
        } else if (unit.right(2) == QLatin1String("ic")) {
            length.unit = KoSvgText::CssLengthPercentage::Ic;
        } else if (unit.right(2) == QLatin1String("lh")) {
            length.unit = KoSvgText::CssLengthPercentage::Lh;
        } else if (unit.right(1) == QLatin1Char('%')) {

            if (percentageViewBox) {
                if (horiz && vert)
                    length.value = (length.value / 100.0) * (sqrt(pow(bbox.width(), 2) + pow(bbox.height(), 2)) / sqrt(2.0));
                else if (horiz)
                    length.value = (length.value / 100.0) * bbox.width();
                else if (vert)
                    length.value = (length.value / 100.0) * bbox.height();
            } else {
                length.value = (length.value / 100.0);
                length.unit = KoSvgText::CssLengthPercentage::Percentage;
            }
        }
    } else {
        length.value = SvgUtil::fromUserSpace(length.value);
    }

    return length;
}

qreal SvgUtil::parseUnitX(SvgGraphicsContext *gc, const KoSvgTextProperties &resolved, const QString &unit)
{
    if (gc->forcePercentage) {
        return SvgUtil::fromPercentage(unit) * gc->currentBoundingBox.width();
    } else {
        return SvgUtil::parseUnit(gc, resolved, unit, true, false, gc->currentBoundingBox);
    }
}

qreal SvgUtil::parseUnitY(SvgGraphicsContext *gc, const KoSvgTextProperties &resolved, const QString &unit)
{
    if (gc->forcePercentage) {
        return SvgUtil::fromPercentage(unit) * gc->currentBoundingBox.height();
    } else {
        return SvgUtil::parseUnit(gc, resolved, unit, false, true, gc->currentBoundingBox);
    }
}

qreal SvgUtil::parseUnitXY(SvgGraphicsContext *gc, const KoSvgTextProperties &resolved, const QString &unit)
{
    if (gc->forcePercentage) {
        const qreal value = SvgUtil::fromPercentage(unit);
        return value * sqrt(pow(gc->currentBoundingBox.width(), 2) + pow(gc->currentBoundingBox.height(), 2)) / sqrt(2.0);
    } else {
        return SvgUtil::parseUnit(gc, resolved, unit, true, true, gc->currentBoundingBox);
    }
}

qreal SvgUtil::parseUnitAngular(SvgGraphicsContext *gc, const QString &unit)
{
    Q_UNUSED(gc);

    qreal value = 0.0;

    if (unit.isEmpty()) return value;
    QByteArray unitLatin1 = unit.toLower().toLatin1();

    const char *start = unitLatin1.data();
    if (!start) return value;

    const char *end = parseNumber(start, value);

    if (int(end - start) < unit.length()) {
        if (unit.right(3) == "deg") {
            value = kisDegreesToRadians(value);
        } else if (unit.right(4) == "grad") {
            value *= M_PI / 200;
        } else if (unit.right(3) == "rad") {
            // noop!
        } else {
            value = kisDegreesToRadians(value);
        }
    } else {
        value = kisDegreesToRadians(value);
    }

    return value;
}

qreal SvgUtil::parseNumber(const QString &string)
{
    qreal value = 0.0;

    if (string.isEmpty()) return value;
    QByteArray unitLatin1 = string.toLatin1();

    const char *start = unitLatin1.data();
    if (!start) return value;

    const char *end = parseNumber(start, value);
    KIS_SAFE_ASSERT_RECOVER_NOOP(int(end - start) == string.length());
    return value;
}

QString SvgUtil::mapExtendedShapeTag(const QString &tagName, const QDomElement &element)
{
    QString result = tagName;

    if (tagName == "path") {
        QString kritaType = element.attribute("krita:type", "");
        QString sodipodiType = element.attribute("sodipodi:type", "");

        if (kritaType == "arc") {
            result = "krita:arc";
        } else if (sodipodiType == "arc") {
            result = "sodipodi:arc";
        }
    }

    return result;
}
