include_guard(GLOBAL)

set(CMAKE_SYSTEM_NAME iOS)

set(KRITA_IOS_PLATFORM "DEVICE" CACHE STRING "iOS target: DEVICE or SIMULATOR")
set_property(CACHE KRITA_IOS_PLATFORM PROPERTY STRINGS DEVICE SIMULATOR)

if(KRITA_IOS_PLATFORM STREQUAL "DEVICE")
    set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "Apple SDK" FORCE)
elseif(KRITA_IOS_PLATFORM STREQUAL "SIMULATOR")
    set(CMAKE_OSX_SYSROOT iphonesimulator CACHE STRING "Apple SDK" FORCE)
else()
    message(FATAL_ERROR "KRITA_IOS_PLATFORM must be DEVICE or SIMULATOR")
endif()

set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "iOS architecture" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 17.0 CACHE STRING "Minimum iOS/iPadOS version" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

# Build tools execute on macOS; libraries, headers, and CMake packages must be
# resolved for the selected iOS SDK/prefix instead of leaking from Homebrew.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)

set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE NO)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO)
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS "iphoneos iphonesimulator")
set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2")
set(CMAKE_XCODE_ATTRIBUTE_DEAD_CODE_STRIPPING YES)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_MODULES YES)
