/*
 * SPDX-FileCopyrightText: 2026 LibrePaint contributors
 * SPDX-License-Identifier: LGPL-2.0-or-later
 */

#ifndef KRITASTORE_EXPORT_H
#define KRITASTORE_EXPORT_H

#include <kritaresourcestorage_export.h>

#define KRITASTORE_EXPORT KRITARESOURCESTORAGE_EXPORT
#define KRITASTORE_NO_EXPORT KRITARESOURCESTORAGE_NO_EXPORT
#define KRITASTORE_DEPRECATED KRITARESOURCESTORAGE_DEPRECATED
#define KRITASTORE_DEPRECATED_EXPORT KRITARESOURCESTORAGE_DEPRECATED_EXPORT
#define KRITASTORE_DEPRECATED_NO_EXPORT KRITARESOURCESTORAGE_DEPRECATED_NO_EXPORT

#endif
