# SPDX-License-Identifier: GPL-2.0-or-later
qt_add_resources(gpu_canvas_resources gpu_canvas.qrc)
add_library(kritacanvasgpurenderer STATIC GpuRenderer.cpp ${gpu_canvas_resources})
target_include_directories(kritacanvasgpurenderer PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(kritacanvasgpurenderer PUBLIC kritaimagegpudocument Qt${QT_MAJOR_VERSION}::Gui)
set_target_properties(kritacanvasgpurenderer PROPERTIES AUTOMOC OFF POSITION_INDEPENDENT_CODE ON)

if((APPLE AND NOT IOS) OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_library(kritacanvasgpusurface STATIC SurfaceRenderer.cpp)
    target_include_directories(kritacanvasgpusurface PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
    target_link_libraries(kritacanvasgpusurface PUBLIC kritacanvasgpurenderer)
    set_target_properties(kritacanvasgpusurface PROPERTIES AUTOMOC OFF POSITION_INDEPENDENT_CODE ON)
    if(APPLE)
        target_sources(kritacanvasgpusurface PRIVATE GpuWindowSurface_mac.mm)
        find_library(LIBREPAINT_GPU_APPKIT AppKit REQUIRED)
        find_library(LIBREPAINT_GPU_QUARTZCORE QuartzCore REQUIRED)
        target_link_libraries(kritacanvasgpusurface PRIVATE ${LIBREPAINT_GPU_APPKIT} ${LIBREPAINT_GPU_QUARTZCORE})
    else()
        target_sources(kritacanvasgpusurface PRIVATE GpuWindowSurface_x11.cpp)
        find_package(X11 REQUIRED)
        target_link_libraries(kritacanvasgpusurface PRIVATE X11::X11)
    endif()
endif()

if(BUILD_TESTING)
    add_subdirectory(tests)
endif()
