add_subdirectory( version )
if(APPLE AND NOT IOS)
    add_subdirectory( macosutils )
endif()
add_subdirectory( global )
add_subdirectory( koplugin )
add_subdirectory( widgetutils )
add_subdirectory( widgets )
add_subdirectory( serialization/xml )
add_subdirectory( resources/storage )
add_subdirectory( flake )
add_subdirectory( basicflakes )
add_subdirectory( pigment )
add_subdirectory( painting )
add_subdirectory( brush )
add_subdirectory( psdutils )
add_subdirectory( color )
add_subdirectory( image )
add_subdirectory( resources )
add_subdirectory( canvas )
add_subdirectory( tools/ui )
add_subdirectory( impex )
add_subdirectory( document )
add_subdirectory( ui )
add_subdirectory( libkis )
add_subdirectory( psd )
add_subdirectory( multiarch )

if (KRITA_USE_SURFACE_COLOR_MANAGEMENT_API)
   add_subdirectory( surfacecolormanagementapi )
endif()
